//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotLiquid.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotLiquid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error in &apos;assign&apos; tag - Valid syntax: assign [var] = [source].
        /// </summary>
        internal static string AssignTagSyntaxException {
            get {
                return ResourceManager.GetString("AssignTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This liquid context does not allow includes..
        /// </summary>
        internal static string BlankFileSystemDoesNotAllowIncludesException {
            get {
                return ResourceManager.GetString("BlankFileSystemDoesNotAllowIncludesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal template name &apos;{0}&apos;.
        /// </summary>
        internal static string LocalFileSystemIllegalTemplateNameException {
            get {
                return ResourceManager.GetString("LocalFileSystemIllegalTemplateNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal template path &apos;{0}&apos;.
        /// </summary>
        internal static string LocalFileSystemIllegalTemplatePathException {
            get {
                return ResourceManager.GetString("LocalFileSystemIllegalTemplatePathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such template &apos;{0}&apos;.
        /// </summary>
        internal static string LocalFileSystemTemplateNotFoundException {
            get {
                return ResourceManager.GetString("LocalFileSystemTemplateNotFoundException", resourceCulture);
            }
        }
    }
}
